# trigger build
version: 2
debug: true
jobs:
  build:
    docker:
      - image: circleci/node:12.22.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: yarn run lint
      - run: yarn run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: circleci/node:12.22.1
    steps:
      - attach_workspace:
          at: .
      - run: npx semantic-release
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
