# trigger build
version: 2
debug: true
jobs:
  build:
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn run build
      - run: yarn run lint
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    docker:
      - image: circleci/node:12.18.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: npm publish
      - run: git config user.name $GITHUB_USERNAME && git config user.email $GITHUB_EMAIL
      - run: npm version patch --force -m "[CI SKIP] Updating the package.json version"
      - run: git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git master
workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
